lend_to_project:
  path:     /lend_to_project/{id}
  defaults:
       { _controller: ProjectBundle:OffreDePret:create_offre_de_pret }
  requirements:
        id: \d+


edit_offre:
  path:   /edit_offre/{id}
  defaults:
       { _controller: ProjectBundle:OffreDePret:edit_offre_de_pret }
  requirements:
        id: \d+


view_offre:
  path:    /view_offre/{id}
  defaults:
       { _controller: ProjectBundle:OffreDePret:view_offre_de_pret }
  requirements:
        id: \d+

accepter_offre:
    path:    /accepter_offre/{id}
    defaults:
       { _controller: ProjectBundle:OffreDePret:accepter_offre }
    requirements:
        id: \d+
