lend_to_project:
  path:     /project/lend_to_project/{id}
  defaults:
       { _controller: ProjectBundle:OffreDePret:create_offre_de_pret }
  requirements:
        id: \d+


edit_offre:
  path:   /project/edit_offre/{id}
  defaults:
       { _controller: ProjectBundle:OffreDePret:edit_offre_de_pret }
  requirements:
        id: \d+


view_offre:
  path:    /project/view_offre/{id}
  defaults:
       { _controller: ProjectBundle:OffreDePret:view_offre_de_pret }
  requirements:
        id: \d+

accepter_offre:
    path:    /project/accepter_offre/{id}
    defaults:
       { _controller: ProjectBundle:OffreDePret:accepter_offre }
    requirements:
        id: \d+
