<?php

namespace ProjectBundle\Repository;

/**
 * OffreDePretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreDePretRepository extends \Doctrine\ORM\EntityRepository
{
}
