index:
    path:     /index
    defaults: { _controller: LeoBundle:Default:index }

pdftest:
    path:     /pdftest/{id}
    defaults: { _controller: LeoBundle:Default:pdftest }
    requirements:
        id: \d+

