project_homepage:
    path:     /project_homepage
    defaults: { _controller: ProjectBundle:Default:index }

create_project:
    path:    /create_project
    defaults: { _controller: ProjectBundle:CreateProject:create_project }